name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        password: ${{ secrets.DO_PASSWORD }}
        script: |
          # Navigate to home directory and create app directory
          cd /home/
          rm -rf autofix-pro-digital-ocean-code
          
          # Clone the latest code
          git clone https://github.com/cmishler108/autofix-pro-digital-ocean-code.git
          cd autofix-pro-digital-ocean-code
          
          # Initialize and update submodules
          git submodule init
          git submodule update --recursive
          
          # Stop and delete all existing PM2 processes
          pm2 stop all || true
          pm2 delete all || true
          pm2 kill || true
          
          # Setup and run frontend
          cd fr
          npm install
          npm run build
          
          # Start frontend with PM2 (Next.js production server)
          pm2 start "npm start" --name "doneez-frontend"
          
          # Setup and run backend
          cd ../DoneEZ
          
          # Install Python dependencies (ensure pip is up to date)
          python3 -m pip install --upgrade pip
          python3 -m pip install --user -r requirements.txt
          
          # Also install system-wide for PM2 to access
          sudo python3 -m pip install -r requirements.txt
          
          # Change to Django project directory
          cd DoneEZ
          
          # Run migrations
          python3 manage.py migrate
          
          # Collect static files
          python3 manage.py collectstatic --noinput || true
          
          # Verify Django installation
          python3 -c "import django; print(f'Django version: {django.get_version()}')"
          
          # Start backend with PM2 (with full path and proper working directory)
          pm2 start "python3 manage.py runserver 0.0.0.0:8000" --name "doneez-backend" --cwd "/root/autofix-pro-digital-ocean-code/DoneEZ/DoneEZ"
          
          # Update nginx configuration
          cd /root/autofix-pro-digital-ocean-code
          sudo cp nginx.conf /etc/nginx/nginx.conf
          
          # Test and reload nginx
          sudo nginx -t && sudo systemctl reload nginx
          
          # Save PM2 configuration
          pm2 save
          pm2 startup