name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        password: ${{ secrets.DO_PASSWORD }}
        script: |
          # Navigate to root directory and clean up
          cd /root/
          
          # Force remove existing directory if it exists
          sudo rm -rf autofix-pro-digital-ocean-code || true
          
          # Clone the latest code
          git clone https://github.com/cmishler108/autofix-pro-digital-ocean-code.git
          cd autofix-pro-digital-ocean-code
          
          echo "Repository cloned successfully. Current directory structure:"
          ls -la
          
          # Stop and delete all existing PM2 processes
          pm2 stop all || true
          pm2 delete all || true
          pm2 kill || true
          
          # Setup and run frontend
          cd fr
          
          # Check if package.json exists and install dependencies
          if [ -f "package.json" ]; then
            echo "Installing frontend dependencies..."
            npm install
            echo "Building frontend..."
            npm run build
          else
            echo "No package.json found in fr directory, checking doneez_front_end..."
            cd doneez_front_end
            npm install
            npm run build
            cd ..
          fi
          
          # Start frontend with PM2 (Next.js production server)
          pm2 start "npm start" --name "doneez-frontend" --cwd "/root/autofix-pro-digital-ocean-code/fr"
          
          # Setup and run backend
          cd DoneEZ
          
          # Verify requirements.txt exists
          echo "Checking requirements.txt..."
          ls -la requirements.txt
          cat requirements.txt
          
          # Create and activate virtual environment
          echo "Creating Python virtual environment..."
          python3 -m venv venv
          source venv/bin/activate
          
          # Install Python dependencies in virtual environment
          echo "Upgrading pip in virtual environment..."
          pip install --upgrade pip
          
          echo "Installing Python dependencies in virtual environment..."
          pip install -r requirements.txt
          
          echo "Verifying Python installation in virtual environment..."
          python --version
          python -c "import sys; print('Python path:', sys.path)"
          python -c "import django; print(f'Django version: {django.get_version()}')"
          pip list | grep -i django
          
          # Change to Django project directory
          cd DoneEZ
          
          # Run Django migrations and collect static files using virtual environment
          echo "Running Django migrations..."
          ../venv/bin/python manage.py migrate
          
          echo "Collecting static files..."
          ../venv/bin/python manage.py collectstatic --noinput
          
          # Verify Django can import properly
          echo "Final Django verification..."
          ../venv/bin/python -c "import django; print(f'Django version: {django.get_version()}')"
          
          # Stop any existing backend process
          pm2 stop doneez-backend || true
          pm2 delete doneez-backend || true
          
          # Start backend with PM2 using virtual environment Python
          echo "Starting Django backend with PM2 using virtual environment..."
          pm2 start "../venv/bin/python manage.py runserver 0.0.0.0:8000" --name "doneez-backend" --cwd "/root/autofix-pro-digital-ocean-code/DoneEZ/DoneEZ"
          
          # Wait a moment and check if backend started successfully
          sleep 3
          pm2 status doneez-backend
          
          # Update nginx configuration
          cd /root/autofix-pro-digital-ocean-code
          sudo cp nginx.conf /etc/nginx/nginx.conf
          
          # Test and reload nginx
          sudo nginx -t && sudo systemctl reload nginx
          
          # Save PM2 configuration
          pm2 save
          pm2 startup