name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        password: ${{ secrets.DO_PASSWORD }}
        script: |
          # Navigate to home directory and create app directory
          cd /home/
          rm -rf autofix-pro-digital-ocean-code
          
          # Clone the latest code
          git clone https://github.com/cmishler108/autofix-pro-digital-ocean-code.git
          cd autofix-pro-digital-ocean-code
          
          # Initialize and update submodules
          git submodule init
          git submodule update --recursive
          
          # Setup and run frontend
          cd fr
          npm install
          npm run build
          
          # Kill existing PM2 processes
          pm2 delete all || true
          
          # Start frontend
          pm2 start npm --name "frontend" -- start
          
          # Setup and run backend
          cd ../DoneEZ/DoneEZ
          
          # Install Python dependencies
          python3 -m pip install -r requirements.txt
          
          # Run migrations
          python3 manage.py migrate
          
          # Start backend
          pm2 start "python3 manage.py runserver 0.0.0.0:8000" --name "backend"
          
          # Save PM2 configuration
          pm2 save
          pm2 startup